Feature/people details is still to change css and personId dosent work at the moment
DorotaZielinska/movies-browser pull request #61
Opened 2023-07-22 08:22 UTC by DorotaZielinska

This is to review, still is small change in css and there will be still update of PeopleDetails index.js and to change slice and saga

2023-07-26 18:34 UTC, MirekSobota commented on src/common/TileList/PeopleDetailsTile/styled.js
> +    box-shadow: 0px 4px 12px 0px rgba(186, 199, 213, 0.5);
I think you should remove this line since it inherits from breakpoint.ipod.

2023-07-26 18:38 UTC, MirekSobota commented on src/features/PeopleDetails/peopleDetailsSaga.js
> +   // console.log("fetchPeopleDetailsSuccess", details);
Please remove these comments before merging.

2023-07-26 18:41 UTC, MirekSobota requested changes
Good job! A website is very well responsive

2023-07-27 07:37 UTC, PawelOwiesek reviewed
Retrieving data from the API looks ok, there are minor differences in figma, and a few lines of commented  code.

2023-07-27 07:37 UTC, PawelOwiesek commented on src/common/TileList/PeopleDetailsTile/index.js
> +        <DescriptionPeople>lorem ipusumloremLiu Yifei was born in Wuhan, Hubei, Province of China on August 25th, 1987. She began modeling at the age of 8 and was trained in singing, dancing and the
??

2023-07-27 07:39 UTC, PawelOwiesek commented on src/common/TileList/PeopleDetailsTile/index.js
> +        <DescriptionPeople>lorem ipusumloremLiu Yifei was born in Wuhan, Hubei, Province of China on August 25th, 1987. She began modeling at the age of 8 and was trained in singing, dancing and the
It's an old version of the code, replaced with props, good job

2023-07-27 09:00 UTC, PawelOwiesek commented on src/features/PeopleDetails/index.js
> +                {screenWidth <= 450 ? "Birth: " : "Date of Birth: "}{" "}
add behavior when no date available
```suggestion
              {details.birthday === null? null
                : details.birthday.split("-").reverse().join(".")}
```suggestion
              {details.birthday === null
```
```

2023-07-27 10:03 UTC, DorotaZielinska commented on src/common/TileList/PeopleDetailsTile/Image/styled.js
> +  width: 399px;
I need to check because how that will be height on responsive part

2023-07-27 10:07 UTC, DorotaZielinska commented on src/features/PeopleDetails/peopleDetailsSaga.js
> +   // console.log("fetchPeopleDetailsSuccess", details);
That part I will remove, because I have a conflict with it, but is important to do that as parts, so that which dosen't work in this line I deleted and console.log

2023-07-27 10:16 UTC, DorotaZielinska commented on src/common/TileList/PeopleDetailsTile/styled.js
> +    box-shadow: 0px 4px 12px 0px rgba(186, 199, 213, 0.5);
Why that should be removed?

2023-07-27 10:55 UTC, DorotaZielinska commented on src/common/TileList/PeopleDetailsTile/styled.js
> +    box-shadow: 0px 4px 12px 0px rgba(186, 199, 213, 0.5);
Now I see was overwritten some part of css code, thanks.

2023-07-27 11:29 UTC, DorotaZielinska commented on src/common/TileList/PeopleDetailsTile/Image/styled.js
> +  width: 399px;
I have removed what was unnecessary at this stage of work and commits. Thanks

2023-07-27 12:50 UTC, DorotaZielinska commented on src/common/TileList/PeopleDetailsTile/Image/styled.js
> +  width: 399px;
The height shuld be auto

2023-07-27 16:10 UTC, MirekSobota approved these changes
Good job!

2023-07-27 16:12 UTC, merged